export const SERVER_NAME = "openclaw-mcp-server";
export const VERSION = "1.0.0";

export const DEFAULT_GATEWAY_URL = "ws://127.0.0.1:18789";
export const DEFAULT_TIMEOUT = 60000;

export const ERROR_CODES = {
  GATEWAY_NOT_CONNECTED: "GATEWAY_NOT_CONNECTED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  RPC_ERROR: "RPC_ERROR",
  TIMEOUT: "TIMEOUT",
} as const;